# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`

AllCops:
  Exclude:
    - "bin/**/*"
    - "vendor/**/*"
    - "db/**/*"
    - "config/**/*"
    - "script/**/*"
    - "spec/rails_helper.rb"

Layout/IndentationStyle:
  EnforcedStyle: tabs
Layout/IndentationWidth:
  Width: 2
Layout/IndentationConsistency:
  Enabled: true
Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false
